### ISSUE TITLE
Mjolnir sometimes crashes when invited to a room the first time

### ISSUE THREAD

**Issue by jaywink** [matrix-org/mjolnir#134]
**Describe the bug**

I installed a fresh mjolnir. The first time I tried to invite it to a room, it crashed. I redacted the invitation, invited again, and it joined the room properly.

Logs:

```
Fri, 24 Sep 2021 21:40:20 GMT [ERROR] [MatrixHttpClient (REQ-2518)] { errcode: 'M_FORBIDDEN', error: 'You are not invited to this room.' }
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<IncomingMessage>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
Fri, 24 Sep 2021 21:40:22 GMT [INFO] [index] Starting bot...
```

**To Reproduce**

Could not reproduce yet. A race?

**Expected behavior**

Bot joins on invite and doesn't crash.

Version: v1.1.20 via Docker Hub images.

The inviting account and Mjolnir are on different homeservers.

**Comment by turt2live** [comment]
This looks like https://github.com/matrix-org/synapse/issues/4345 

Usually bots and bridges work around this by just retrying invites (in the bot-sdk this would be the `AutoJoinRoomsMixin`), but Mjolnir applies custom handling on this due to the config. We might need to handle retries a bit better.
