### ISSUE TITLE
ability to autoredact all new images in x room for the next n minutes

### ISSUE THREAD

**Issue by jesopo** [matrix-org/mjolnir#148]

**Comment by jimmackenzie** [comment]
Possibly use runtime adjustment of nsfw protection instead?
Separate protection to remove all images?

Timed expiry feels less useful.

**Comment by H-Shay** [comment]
> Separate protection to remove all images?

We currently have the MessageIsMedia protection, which auto-redacts any new images/video while enabled. 

The main differentiation from that and this issue seems to be: the ability to scope it to a single room, and the timed aspect of it (which was thought to be less useful?) - is it still worth it to implement?

**Comment by turt2live** [comment]
If `MessageIsMedia` is reliable, then I'd say we can use that instead of writing new code.

**Comment by H-Shay** [comment]
I'll add some tests then to verify it's working and remains working.

**Comment by H-Shay** [comment]
https://github.com/matrix-org/mjolnir/pull/545
