### ISSUE TITLE
Protected room list doesn't use aliases

### ISSUE THREAD

**Issue by turt2live** [matrix-org/mjolnir#58]

**Comment by Gnuxie** [comment]
Not sure what the history of this issue is, or what is expected. Currently when you ban via an alias `!mjolnir ban list #foo:example.com` the alias will get put into the list.

I guess one issue is that we also want the alias to be resolved and both the alias and the room id be put into the list as separate entries?

And should the opposite be true if the room has a canonical alias? (i.e. `!mjolnir ban list https://matrix.to/#/!tLjcIjtrjzYNvUgnxX:localhost:9999?via=example.com` both room id and canonical alias get put into the list)

**Comment by turt2live** [comment]
I also don't know what this means.
